version: "3.9"
name: xmart
services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
    ports:
      - "8000:8000"  # Expose container port 8000 to host port 8000
    volumes:
      - ./app:/app  
    networks:
      - my-api-net
    env_file:
      - ./app/.env
    environment:
      - PYTHONUNBUFFERED=1

  postgres_db:
    image: postgres:latest  # Use the official PostgreSQL image
    restart: always
    container_name: PostgresCont
    ports:
      - '5433:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - my-api-net
    env_file:
      - ./app/.env

volumes:
  postgres_db:
    driver: local

networks:
  my-api-net:  # Define the custom network
